### ISSUE TITLE
Bug: Variable "version" is not defined

### ISSUE THREAD

**Issue by bbalaji-ucsd** [mlab-upenn/pyEp#3]
https://github.com/mlab-upenn/pyEp/blob/f3b4301249c05112f586bd276d457d5373666213/pyEp/pyEp/pyEpError.py#L12

**Comment by dnong** [comment]
This has been fixed, although I am curious which version of EnergyPlus does not use the ExternalInterface like this.

**Comment by bbalaji-ucsd** [comment]
I'm using version 8.8
